apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmark-config
  # namespace: <YOUR_NAMESPACE>
data:
  MODEL_NAME: "facebook/opt-6.7b"
  NUM_REPLICAS: "30"
  MEM_POOL_SIZE: "32GB"
  BENCHMARK_TYPE: "random"
  STORAGE_PATH: "/models"
  RESULTS_PATH: "/results"
  GENERATE_PLOTS: "false"
  KEEP_ALIVE: "false"
